server:
  port: 8003


spring:
  profiles:
    active: dev
  servlet:
    multipart:
      #单次最大上传单个文件大小为1G，单次最大总上传大小为1G
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-vod


aliyun:
  vod:
    file:
      keyid: LTAI4GGqF9Guxdk23menv6WQ
      keysecret: 0uYIaBhR6R0LKnv2zmwbHdgjBU8ckN
