#端口号
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#阿里云oss相关配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI4GHPWWP6vqMvXoEqqu2h
      keysecert: YUT1L4uwQLe0SOb4OphHLpK5OP4kff
      bucketname: guli-edu-avatar