#端口号
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#阿里云oss相关配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI4GGqF9Guxdk23menv6WQ
      keysecert: 0uYIaBhR6R0LKnv2zmwbHdgjBU8ckN
      bucketname: guli-edu-avatar