#端口号
server:
  port: 8001
#服务名
spring:
  application:
    name: service-edu
  #开发环境
  profiles:
    active: dev
  #数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #开启微服务，注册中心nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #redis相关配置
  redis:
    host: 106.13.35.155
    port: 6379
    database: 0
    timeout: 1800000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  #mapper.xml文件绑定配置
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml

#设置日志级别
logging:
  level:
    root: info
#开启服务熔断机制
feign:
  hystrix:
    enabled: true
#设置超时时间，不设置默认时间为1000毫秒（1秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000