server:
  port: 8005
spring:
  application:
    name: service-msm
  redis:
    host: 106.13.35.155
    port: 6379
    database: 0
    timeout: 1800000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848