mybatis-plus:
  mapper-locations: classpath:com/atguigu/orderservice/mapper/xml/*.xml
server:
  port: 8007
spring:
  application:
    name: service-order
  #开发环境
  profiles:
    active: dev
  #数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #开启微服务，注册中心nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  hystrix:
    enabled: true
#设置超时时间，不设置默认时间为1000毫秒（1秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000